drop table JOBS_TEST;
CREATE TABLE "JOBS_TEST"
  (
    "JOB_ID"     VARCHAR2(10),
    "JOB_TITLE"  VARCHAR2(35) NOT NULL ENABLE,
    "MIN_SALARY" NUMBER(6,0),
    "MAX_SALARY" NUMBER(6,0),
    CONSTRAINT "JOBS_TEST_PK" PRIMARY KEY ("JOB_ID")
  )